cache:
    path: /home/crimsonknave/.local/state/gh-not/cache.json
    ttl_in_hours: 1
endpoint:
    all: true
    max_page: 5
    max_retry: 10
    per_page: 100
keymap:
    command:
        command accept:
            - enter
        command cancel:
            - esc
    filter:
        filter accept:
            - enter
        filter cancel:
            - esc
    normal:
        command mode:
            - ':'
        cursor down:
            - down
            - j
        cursor up:
            - up
            - k
        filter mode:
            - /
        force quit:
            - ctrl+c
        go to end:
            - end
            - G
        go to start:
            - home
            - g
        next page:
            - right
            - l
        open in browser:
            - o
        previous page:
            - left
            - h
        quit:
            - q
            - esc
        select all:
            - a
        select none:
            - A
        toggle help:
            - '?'
        toggle selected:
            - ' '
            - x
rules: 
  - name: test
    filter: .author.handle == crimsonknave
view:
    height: 40
